version: '3.9'

services:
  db:
    container_name: db
    image: postgres:13-alpine
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      TZ: ${WORKSPACE_TIMEZONE}
      PGDATA: /var/lib/postgresql/data/pgdata/
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata:
